name: "install with cpm"
description: "install Perl Modules using App::cpm"
branding:
  icon: "arrow-right"
  color: "blue"
inputs:
  install:
    description: "List of modules or distributions to install [seperated by newline]"
    required: false

  cpanfile:
    description: "Use a cpanfile to install modules"
    required: false

  tests:
    description: "Run or not the unit tests"
    required: false
    default: false

  global:
    description: "Perform a global or local installation: -g"
    required: false
    default: true

  args:
    description: "Extra args used passed to install command"
    required: false

  sudo:
    description: "Perform installations as root"
    required: false
    default: true

  verbose:
    description: "Run cpm with -v flag or not"
    required: false
    default: false

  perl:
    description: "Path of perl to use default to currtent PATH"
    required: false
    default: "perl"

  path:
    description: "Path where to install cpm: the string can use $Config values"
    required: false
    default: "$Config{installsitescript}/cpm"

  version:
    description: "Which version to install"
    required: false
    default: "main"

runs:
  using: "node20"
  main: "dist/index.js"
