name: Lint javascript
on:
    push:
        paths:
            - '*.js'
            - '.github/workflows/lint-javascript.yml'
            - 'eslint.config.js'
            - 'package*'
    pull_request:
        paths:
            - '*.js'
            - '.github/workflows/lint-javascript.yml'
            - 'eslint.config.js'
            - 'package*'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint javascript
              run: npm run lint
